// The band's repertoire as first-run seed data, transcribed from the real
// "Amanda & Dave - Crescent Head" setlist. Used only when localStorage is
// empty; from then on the library belongs to the user.
// eslint-disable-next-line no-unused-vars
const SEED_LIBRARY = [
  { title: 'Tennessee Whiskey', key: 'A', singer: 'Chris' },
  { title: 'Rhiannon', key: 'Em', singer: 'Chris' },
  { title: 'On Fire', key: 'E', singer: 'Chris' },
  { title: 'Two Strong Hearts', key: 'G#m', singer: 'Chris', note: '1st chord G#m' },
  { title: 'Sunsets', key: 'A', singer: 'Chris' },
  { title: 'Steal My Kisses', key: 'G', singer: 'Chris' },
  { title: 'Knees', key: 'C', singer: 'Chris' },
  { title: 'Dreams', key: 'A', singer: 'Chris' },
  { title: 'Jack & Diane', key: 'A', singer: 'Chris' },
  { title: 'Give Me One Reason', key: 'E', singer: 'Chris', note: 'slow funky version' },
  { title: 'My Happiness', key: 'C', singer: 'Chris' },
  { title: 'Dancing In The Dark', key: 'A', singer: 'Chris' },
  { title: 'Take It Easy', key: 'G', singer: 'Chris' },
  { title: 'Unchain My Heart', key: 'Am', singer: 'Chris' },
  { title: 'Summertime', key: 'Eb', singer: 'Chris' },
  { title: '3am', key: 'G#', singer: 'Chris' },
  { title: 'To Her Door', key: 'G', singer: 'Chris' },
  { title: 'Listen To The Music', key: 'A', singer: 'Chris' },
  { title: 'Mystify', key: 'C', singer: 'Chris' },
  { title: 'Brown Eyed Girl', key: 'G', singer: 'Jerry' },
  { title: 'Cherry Bomb', key: 'G', singer: 'Chris', note: 'John Mellencamp' },
  { title: 'Hurt So Good', key: 'G', singer: 'Chris' },
  { title: 'Rain', key: 'D', singer: 'Chris', note: 'full step down' },
  { title: 'Sultans Of Swing', key: 'Dm', singer: 'Chris' },
  { title: 'Copperhead Road', key: 'D', singer: 'Chris' },
  { title: 'Never Tear Us Apart', key: 'Am', singer: 'Chris' },
  { title: 'Chicken Fried', key: 'G', singer: 'Chris' },
  { title: 'Walk Of Life', key: 'E', singer: 'Chris' },
  { title: 'Lover Lover, You Dont Treat Me No Good', key: 'B', singer: 'Chris' },
  { title: 'Superstition', key: 'D', singer: 'Jerry' },
  { title: 'Summer Of 69', key: 'C', singer: 'Chris' },
  { title: '9 to 5', key: 'A', singer: 'Chris' },
  { title: 'April Sun', key: 'A', singer: 'Jerry' },
  { title: 'Crazy Little Thing Called Love', key: 'D', singer: 'Chris' },
  { title: 'Folsom Prison', key: 'E', singer: 'Chris' },
  { title: 'Little Lion Man', key: 'F', singer: 'Chris' },
  { title: 'Midnight Special', key: 'G', singer: 'Chris', note: 'faster tempo than usual' },
  { title: 'Whats My Age Again?', key: 'G', singer: 'Chris' },
  { title: 'Dumb Things', key: 'Am', singer: 'Chris' },
  { title: 'Play That Funky Music', key: 'D', singer: 'Jerry' },
  { title: 'La Bamba', key: 'C', singer: 'Chris' },
  { title: 'Shake A Tail Feather', key: 'B', singer: 'Chris' },
  { title: 'Love Story', key: 'G', singer: 'Chris' },
  { title: 'Old Time Rock N Roll', key: 'A', singer: 'Chris' },
  { title: 'Johnny B. Goode', key: 'Bb', singer: 'Chris' },
  { title: 'Mr Brightside', key: 'A', singer: 'Chris' },
  { title: 'Call Me Al', key: 'F', singer: 'Jerry' },
  { title: 'Sex On Fire', key: 'E', singer: 'Chris' },
  { title: 'Sweet Caroline', key: 'C', singer: 'Chris' },
  { title: 'Hot Hot Hot', key: 'F', singer: 'Jerry' },
  { title: 'First Date', key: 'C', singer: '' },
  { title: 'Dammit', key: 'C', singer: '' },
  { title: 'No Diggity', key: 'Gm', singer: '' },
];
