// The band's repertoire as first-run seed data, transcribed from the
// real "TSWB Song list and keys" sheet. Used only when localStorage is
// empty; from then on the library belongs to the user.
//
// `sung` is a comma-separated list of who sings it and the key they
// take it in - "Chris A, Adam G" - because a song can belong to more
// than one singer, each in their own key. A name on its own means that
// singer with no key recorded. app.js expands it into the song's parts.
// eslint-disable-next-line no-unused-vars
const SEED_LIBRARY = [
  { title: 'Tennessee Whiskey', sung: 'Chris A, Adam G, Church A' },
  { title: 'Rhiannon', sung: 'Chris Em, Adam Dm' },
  { title: 'On Fire', sung: 'Chris E' },
  { title: 'Two Strong Hearts', sung: 'Chris G#m, Miranda Bm', note: '1st chord G#m' },
  { title: 'Sunsets', sung: 'Chris A' },
  { title: 'Steal My Kisses', sung: 'Chris G, Adam G' },
  { title: 'Knees', sung: 'Chris C' },
  { title: 'Dreams', sung: 'Chris A, Adam E, Jerry F, Miranda C' },
  { title: 'Jack & Diane', sung: 'Chris A' },
  { title: 'Give Me One Reason', sung: 'Chris E, Adam E', note: 'slow funky version' },
  { title: 'My Happiness', sung: 'Chris C' },
  { title: 'Dancing In The Dark', sung: 'Chris A, Adam G' },
  { title: 'Take It Easy', sung: 'Chris G, Adam E' },
  { title: 'Unchain My Heart', sung: 'Chris Am' },
  { title: 'Summertime', sung: 'Chris Eb' },
  { title: '3am', sung: 'Chris G#, Adam G' },
  { title: 'To Her Door', sung: 'Chris G, Adam G, Church G' },
  { title: 'Listen To The Music', sung: 'Chris A, Adam A' },
  { title: 'Mystify', sung: 'Chris C' },
  { title: 'Brown Eyed Girl', sung: 'Jerry G, Chris G, Adam G, Church G' },
  { title: 'Cherry Bomb', sung: 'Chris G', note: 'John Mellencamp' },
  { title: 'Hurt So Good', sung: 'Chris G, Church G' },
  { title: 'Rain', sung: 'Chris D', note: 'full step down' },
  { title: 'Sultans Of Swing', sung: 'Chris Dm' },
  { title: 'Copperhead Road', sung: 'Chris D' },
  { title: 'Never Tear Us Apart', sung: 'Chris Am, Adam Am' },
  { title: 'Chicken Fried', sung: 'Chris G, Church G' },
  { title: 'Walk Of Life', sung: 'Chris E' },
  { title: 'Lover Lover, You Dont Treat Me No Good', sung: 'Chris B, Adam G' },
  { title: 'Superstition', sung: 'Jerry D, Adam Eb, Church Eb' },
  { title: 'Summer Of 69', sung: 'Chris C' },
  { title: '9 to 5', sung: 'Chris A, Adam A, Miranda G' },
  { title: 'April Sun', sung: 'Jerry A, Chris A, Adam G, Church A' },
  { title: 'Crazy Little Thing Called Love', sung: 'Chris D' },
  { title: 'Folsom Prison', sung: 'Chris E' },
  { title: 'Little Lion Man', sung: 'Chris F' },
  { title: 'Midnight Special', sung: 'Chris G', note: 'faster tempo than usual' },
  { title: 'Whats My Age Again?', sung: 'Chris G' },
  { title: 'Dumb Things', sung: 'Chris Am, Adam Am' },
  { title: 'Play That Funky Music', sung: 'Jerry D, Church E' },
  { title: 'La Bamba', sung: 'Chris C' },
  { title: 'Shake A Tail Feather', sung: 'Chris B' },
  { title: 'Love Story', sung: 'Chris G, Adam G' },
  { title: 'Old Time Rock N Roll', sung: 'Chris A, Adam A' },
  { title: 'Johnny B. Goode', sung: 'Chris Bb, Adam A' },
  { title: 'Mr Brightside', sung: 'Chris A, Adam A' },
  { title: 'Call Me Al', sung: 'Jerry F' },
  { title: 'Sex On Fire', sung: 'Chris E, Adam D' },
  { title: 'Sweet Caroline', sung: 'Chris C, Adam C, Jerry C' },
  { title: 'Hot Hot Hot', sung: 'Jerry F' },
  { title: 'First Date', sung: 'Chris C' },
  { title: 'Dammit', sung: 'Chris C' },
  { title: 'No Diggity', sung: 'Chris Gm, Adam Gm' },
  { title: '500 miles', sung: 'Chris E' },
  { title: 'Achy Breaky Heart', sung: 'Chris A, Adam A' },
  { title: 'Ain\'t No Mountain', sung: 'Chris Bm' },
  { title: 'All night long', sung: 'Chris G, Adam G' },
  { title: 'Bad Moon Rising', sung: 'Chris C' },
  { title: 'Beer Never Broke My Heart', sung: 'Chris D' },
  { title: 'Better Man', sung: 'Chris D, Adam D' },
  { title: 'Blame It On The boogie', sung: 'Adam E' },
  { title: 'Blister In The Sun', sung: 'Chris G' },
  { title: 'Boot Scootn’ Boogie', sung: 'Chris E' },
  { title: 'Boys Light Up', sung: 'Chris Bm' },
  { title: 'Chain reaction', sung: 'Chris G' },
  { title: 'Chatahoochie', sung: 'Chris C' },
  { title: 'Closing Time', sung: 'Chris G' },
  { title: 'Come Said The Boy', sung: 'Chris Am' },
  { title: 'Country Roads', sung: 'Chris G, Adam G, Church G' },
  { title: 'Cry to me', sung: 'Chris C' },
  { title: 'Day Drunk', sung: 'Chris A, Adam A' },
  { title: 'Dont Dream Its Over', sung: 'Miranda Eb' },
  { title: 'Drops Of Jupiter', sung: 'Chris A, Adam E' },
  { title: 'Eagle rock', sung: 'Chris A' },
  { title: 'Everlong', sung: 'Chris D, Adam D' },
  { title: 'everything', sung: 'Chris D' },
  { title: 'Faith', sung: 'Adam A, Church C, Jerry C' },
  { title: 'Fast Car', sung: 'Chris A, Adam A' },
  { title: 'Footloose', sung: 'Church A' },
  { title: 'Forever you and Me', sung: 'Chris G' },
  { title: 'Free fallin', sung: 'Chris E, Church F' },
  { title: 'Gambler', sung: 'Chris Eb' },
  { title: 'Get Lucky', sung: 'Chris Am, Adam Bm, Jerry Bm' },
  { title: 'Gimme Gimme Gimme', sung: 'Chris Am' },
  { title: 'Good Golly Miss Molly', sung: 'Chris C' },
  { title: 'Gold on the ceiling', sung: 'Chris G, Church G' },
  { title: 'Have I Told You lately', sung: 'Chris G' },
  { title: 'Have you ever seen the rain', sung: 'Chris A' },
  { title: 'Higher and Higher', sung: 'Chris E' },
  { title: 'Honkey Tonk Woman', sung: 'Chris G' },
  { title: 'Horses', sung: 'Miranda B' },
  { title: 'I knew I loved You', sung: 'Chris G' },
  { title: 'I\'m Yours', sung: 'Chris A' },
  { title: 'Isn\'t She Lovely', sung: 'Adam Em, Miranda C#m' },
  { title: 'Keh San', sung: 'Miranda G' },
  { title: 'Kiss', sung: 'Adam A' },
  { title: 'Last night', sung: 'Chris G' },
  { title: 'Lay down sally', sung: 'Chris A' },
  { title: 'Learning to Fly', sung: 'Chris C, Church C' },
  { title: 'Leave Your Hat On', sung: 'Chris C' },
  { title: 'Livin On A Prayer', sung: 'Chris Am, Adam Am, Miranda Em' },
  { title: 'Long cool woman' },
  { title: 'Lookin Out my Back Door', sung: 'Chris A' },
  { title: 'Love Is In The Air', sung: 'Miranda C' },
  { title: 'Mix Em With Whiskey', sung: 'Chris G' },
  { title: 'Mr Jones', sung: 'Chris Am' },
  { title: 'Mustang Sally', sung: 'Chris B, Jerry A' },
  { title: 'My Girl', sung: 'Adam C' },
  { title: 'Nutbush', sung: 'Chris A, Miranda A' },
  { title: 'Power of love', sung: 'Jerry A' },
  { title: 'Proud Mary', sung: 'Chris A, Adam A' },
  { title: 'Ride Wit Me (nelly)' },
  { title: 'Run To paradise', sung: 'Miranda A' },
  { title: 'Sand In My boots', sung: 'Adam C' },
  { title: 'Say That You Love Me', sung: 'Chris G' },
  { title: 'Sexual Healing', sung: 'Chris C, Adam C', note: '*G-Am-F-C' },
  { title: 'Shook Me All Night Long', sung: 'Chris G, Miranda G' },
  { title: 'Simply the Best', sung: 'Chris A, Adam A, Miranda F' },
  { title: 'Sledgehammer', sung: 'Chris Ebm' },
  { title: 'Somebody Like You', sung: 'Chris E, Adam E' },
  { title: 'Something in the orange', sung: 'Chris Em, Adam Em' },
  { title: 'Something Like Olivia', sung: 'Chris G, Adam G' },
  { title: 'Smooth (rob thomas)' },
  { title: 'Soul to squeeze', sung: 'Chris F' },
  { title: 'Stand By Me', sung: 'Chris A, Adam G, Miranda A' },
  { title: 'Stuck In The Middle', sung: 'Chris D, Adam C' },
  { title: 'Sunday Morning', sung: 'Chris A, Adam G' },
  { title: 'Suzie Q', sung: 'Chris E' },
  { title: 'Sweat', sung: 'Chris C' },
  { title: 'Sweet Home Alabama', sung: 'Chris D, Adam D, Jerry A' },
  { title: 'Sweet Pea', sung: 'Chris E, Adam E' },
  { title: 'That\'s what i like about you', sung: 'Chris E' },
  { title: 'The Kinda Love We Make', sung: 'Chris Am, Adam Gm' },
  { title: 'Them Stems', sung: 'Chris G' },
  { title: 'The Way', sung: 'Chris F#m' },
  { title: 'Tip of My Tongue', sung: 'Chris B, Adam B' },
  { title: 'Tutti Fruiti', sung: 'Chris C' },
  { title: 'Uptown Funk', sung: 'Adam Bm, Jerry Bbm' },
  { title: 'Valerie', sung: 'Chris Bb, Adam Bb, Miranda Eb' },
  { title: 'Wagon Wheel', sung: 'Chris A, Adam G' },
  { title: 'Wake Me Up', sung: 'Chris Bm, Adam F#m' },
  { title: 'Walking In Memphis', sung: 'Adam B' },
  { title: 'Walking On Sunshine', sung: 'Chris E' },
  { title: 'Weather With You', sung: 'Chris Em, Adam Em' },
  { title: 'When It rains It Pours', sung: 'Chris G, Adam G' },
  { title: 'Wicked Games', sung: 'Chris Bm, Adam Bm, Jerry Bm' },
  { title: 'Won\'t Back Down', sung: 'Chris G' },
  { title: 'Wonderwall', sung: 'Chris F#m' },
  { title: 'You Got It', sung: 'Chris G' },
  { title: 'You Send Me', sung: 'Chris Em' },
  { title: 'You SHould Probably Leave', sung: 'Chris A' },
  { title: 'Your Body is a Wonderland', sung: 'Chris F, Adam F, Jerry F' },
];
